trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
#trainset_3d: ['Human36M']
#trainset_2d: ['MSCOCO']
testset: 'PW3D'

lr_dec_epoch: [10]
end_epoch: 14
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10
#render: True
test_batch_size: 64

edge_module: False
SMPL_edge: False
distillation_module: False
distillation_pretrained: False
distillation_loss: ""
dilstillation_edge: ""
distillation_pretrained: False
canny_edge: False
nothing: False
demo: False
human_parsing: True
origin: True
# test
inference_testing: True