trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
#trainset_3d: ['Human36M']
#trainset_2d: ['MSCOCO']
testset: 'RH_dataset'

lr_dec_epoch: [10]
end_epoch: 14
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10
origin: False
inference_testing: True
crowd: True
distillation_module: True
distillation_pretrained: True
distillation_loss: "log_softmax_l1"
dilstillation_edge: "Canny"
distillation_pretrained: True
demo: False
test_train: True