#trainset_3d: ['Human36M', 'MuCo']
#trainset_2d: ['MSCOCO', 'MPII']
trainset_3d: ['Human36M']
trainset_2d: ['MSCOCO']
testset: 'PW3D'
cliff: True
lr_dec_epoch: [10,15]
end_epoch: 20
lr: 0.001
lr_backbone: 0.0001
lr_dec_factor: 10
#render: True
origin: True
#crowd: True
#test_train: True\
SMPL_overlap: False
Backbone_model: 'resnet'
SMPL_edge: False
distillation_module: False
distillation_pretrained: False
distillation_loss: ""
dilstillation_edge: ""
distillation_pretrained: False
pidinet_edge: False
nothing: True
demo: False
first_input: False
edge_module: False
# test
inference_testing: False