trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
#trainset_3d: ['Human36M']
#trainset_2d: ['MSCOCO']
testset: 'OCHuman'

lr_dec_epoch: [10]
end_epoch: 14
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10
#render: True
origin: False
crowd: True
test_train: True

distillation_module: False
distillation_pretrained: False
distillation_loss: ""
dilstillation_edge: ""
distillation_pretrained: False
pidinet_edge: False
nothing: True
demo: False
first_input: False
# test
inference_testing: True