trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
#trainset_3d: ['MuCo']
#trainset_2d: ['MSCOCO']
testset: 'PW3D'

lr_dec_epoch: [10,15]
end_epoch: 20
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10
#render: True
SMPL_edge: False
SMPL_overlap: False
distillation_module: False
distillation_pretrained: False
distillation_loss: ""
dilstillation_edge: ""
distillation_pretrained: False
canny_edge: False
nothing: False
human_parsing: True
demo: False
# test
inference_testing: False