trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'MPII']
testset: 'PW3D'

lr_dec_epoch: [4,6]
end_epoch: 10
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10
#render: True

SMPL_edge: False
SMPL_overlap: False
distillation_module: False
distillation_pretrained: False
distillation_loss: ""
dilstillation_edge: ""
distillation_pretrained: False
HED_edge: True
nothing: True
demo: False

# test
inference_testing: False